spring:
  datasource:
    url: jdbc:log4jdbc:mysql://127.0.0.1:3306/accessadd?useUnicode=true&characterEncoding=utf-8
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: root
    password: 123456
    hikari:
      max-lifetime: 30000

server:
  port: 9070
  servlet:
    context-path: /access

proxy:
  url:
    list: http://127.0.0.1:12100/proxy/ip/list/50
    remove: http://127.0.0.1:12100/proxy/ip/remove/